spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/kalaha
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false